### ISSUE TITLE
fix: я здесь железный человек

### ISSUE THREAD

**Issue by Siirko** [Ratiscrum-V2/rts-app-2022#16]
Здравствуйте, есть некоторые проблемы с изображением, которые я не вижу, но на самом деле я хотел посмотреть на это место с женой, но на самом деле я здесь железный человек. 

da
@jvondermarck give me the rust command from time to tinme si ta un spritz dans la gueule

**Comment by Siirko** [comment]
@bricklou

**Comment by Kayn017** [comment]
Bing chilling

**Comment by jvondermarck** [comment]
yeah
